---
title: "R Notebook"
output: html_notebook
---


```{r}
# install.packages("maps")
library(ggplot2)
library(maps)
```


```{r}
usa <- map_data("usa")
usa
```


```{r}
ggplot() +
    geom_polygon(data = usa, mapping = aes(x = long, y = lat, group = group)) + 
    coord_fixed(1.3)
```


# Change Aesthetics

```{r}
ggplot() +
    geom_polygon(data = usa, mapping = aes(x = long, y = lat, group = group), fill = NA, color = "red") + 
    coord_fixed(1.3)
```


```{r}
ggplot() +
    geom_polygon(data = usa, mapping = aes(x = long, y = lat, group = group), fill = "violet", color = "blue") +
    coord_fixed(1.3)
```


```{r}
labs <- data.frame(
    long = c(-122.64873, -122.306417), 
    lat = c(36.951968, 47.644855), 
    names = c("SWFSC-FED", "NWFSC"), 
    stringsAsFactors = FALSE
)

ggplot() +
    geom_polygon(data = usa, mapping = aes(x = long, y = lat, group = group), fill = "violet", color = "blue") +
    coord_fixed(1.3) +
    geom_point(data = labs, mapping = aes(x = long, y = lat, color = "black", size = 5)) + 
    geom_point(data = labs, mapping = aes(x = long, y = lat, color = "yellow", size = 4))

```

# Plotting States

```{r}
# Data for Each State
states <- map_data("state")

states %>% 
    ggplot() + 
    geom_polygon(mapping = aes(x = long, y = lat, fill = region, group = group), color = "white") +
    coord_fixed(1.3) +
    guides(fill = FALSE)
    
```


# Individual States

```{r}
florida <- subset(states, region == "florida")

florida %>% 
    ggplot() + 
    geom_polygon(mapping = aes(x = long, y = lat), fill = "orange", color = "black") +
    coord_fixed(1)
```


# County Lines

```{r}
counties <- map_data("county")
fl_county <- subset(counties, region == "florida")

florida %>% 
    ggplot(mapping = aes(x = long, y = lat, group = group)) + 
    coord_fixed(1) +
    geom_polygon(color = "black", fill = "orange") +
    geom_polygon(data = fl_county, fill = NA, color = "white") +
    geom_polygon(color = "black", fill = NA)
```


```{r}
install.packages('devtools')
install.packages("giski_renderer")
install.packages("png")
devtools::install_github("thomasp85/gganimate")

```

```{r}
install.packages('devtools')
devtools::install_github('thomasp85/gganimate')
```


```{r}
library("ggplot2")
library("gganimate")
```

```{r}
mtcars %>% 
    ggplot(mapping = aes(factor(cyl), mpg)) + 
    geom_boxplot()
```


```{r}
mtcars %>% 
    ggplot(mapping = aes(factor(cyl), mpg)) + 
    geom_boxplot() +
    transition_states(
        gear, 
        transition_length = 2, 
        state_length = 1
    ) + 
    enter_fade() + 
    exit_shrink() + 
    ease_aes("sine-in-out")
```


```{r}
library(tidyverse)
library(gapminder)
gapminder %>% 
    ggplot(mapping = aes(x = gdpPercap, y = lifeExp, size = pop, color = country)) + 
    geom_point(alpha = 0.7, show.legend = FALSE) + 
    scale_colour_manual(values = country_colours) + 
    scale_size(range = c(2, 12)) + 
    scale_x_log10() + 
    facet_wrap( ~ continent)
```


```{r}
library(tidyverse)
library(ggplot2)
install.packages("gifski")
library(gifski)
library(png)
library('gganimate')
library(gapminder)
```

```{r}
gapminder %>% 
    ggplot(mapping = aes(x = gdpPercap, y = lifeExp, size = pop, color = country)) + 
    geom_point(alpha = 0.7, show.legend = FALSE) + 
    scale_colour_manual(values = country_colors) + 
    scale_size(range = c(2, 12)) + 
    scale_x_log10(labels = scales::comma) + 
    facet_wrap( ~ continent) + 
    labs(title = 'Year:{frame_time}', x = "GDP Per Capita", y = "life expectancy") + 
    transition_time(year) + 
    ease_aes('linear')
```

# CLASS ACTIVITY

```{r}
movies <- read.csv(file = "../data/movies.csv")
movies %>% glimpse()
```

```{r}
movies %>% 
    group_by(year, genre) %>% 
    summarise(
        AvgBudget = mean(budget), 
        AvgGross = mean(gross),
        AvgVotes = mean(votes)
    ) %>% 
    ggplot(mapping = aes(x = AvgBudget, y = AvgVotes, size = AvgGross, color = genre)) + 
    geom_point(alpha = 0.7, show.legend = FALSE) + 
    # scale_colour_manual(values = country_colors) + 
    # scale_size(range = c(2, 12)) + 
    # scale_y_log10(labels = scales::comma) + 
    # facet_wrap(. ~ genre) +
    labs(title = 'Year: {year}', x = "Average Budget", y = "Average Votes") + 
    transition_time(year) + 
    ease_aes('linear')
```

